### ISSUE TITLE
Wrong buffer allocation in icns-encoder.js

### ISSUE THREAD

**Issue by mn4367** [fiahfy/packbits#1]
Line 8-10 of `icns-encoder.js`:

```
const buf = Buffer.alloc(1)
buf[0] = buffer.length - i
buf[1] = byte
```

Shouldn't that be `Buffer.alloc(2)`?

Apart from that, I'm trying to use the ICNS encoder for writing the `il32` and `is32` chunks for an Apple ICNS file but these types don't show up in the generated output file (they appear blank, not even scrambled). The input for these types is an ARGB bitmap (4 bytes for each pixel with A being an alpha channel). But your code only seems to handle 3 byte RBG bitmaps, or am I missing something?

**Comment by fiahfy** [comment]
It works, but Line 10 is unnecessary, so I will fix it.  
  
This module encode binary with RLE algorithm for ICNS, but does not encode whole ARGB bitmap.  
You need to encode binary with each color mask.  

e.g.
```
    import { encode } from '@fiahfy/packbits'

    const data = ...// bitmap buffer
    const height = ...// bitmap height (px)
    const width = ...// bitmap width (px)

    const alphaData = []
    const redData = []
    const greenData = []
    const blueData = []
    for (let y = 0; y < height; y++) {
      for (let x = 0; x < width; x++) {
        const pos = (y * width + x) * 4
        const red = data.slice(pos, pos + 1)
        const green = data.slice(pos + 1, pos + 2)
        const blue = data.slice(pos + 2, pos + 3)
        const alpha = data.slice(pos + 3, pos + 4)
        alphaData.push(alpha)
        redData.push(red)
        greenData.push(green)
        blueData.push(blue)
      }
    }

    const encodedAlpha = encode(Buffer.concat(alphaData, alphaData.length), { icns: true })
    const encodedRed = encode(Buffer.concat(redData, redData.length), { icns: true })
    const encodedGreen = encode(Buffer.concat(greenData, greenData.length), { icns: true })
    const encodedBlue = encode(Buffer.concat(blueData, blueData.length), { icns: true })

    const list = [encodedAlpha, encodedRed, encodedGreen, encodedBlue]
    const totalLength = list.reduce((carry, buffer) => carry + buffer.length, 0)
    const encodedData = Buffer.concat(list, totalLength)
```

Thanks for your report.

**Comment by mn4367** [comment]
Thanks so much for helping me out with this! I'm now able to create `ic04`, `ic05` and also `is32` and `il32` icons properly. The trick with `ic04` and `ic05` seems to be that the order of the icon chunks in the generated file is relevant (for what ever reason), in wrong order they display scrambled. Unfortunately these types seem to supported only on macOS 10.14 (and probably newer), so I resorted to `is32` and `il32` which are supported even on very old version of macOS. I can tell If you are interested in how to create them.
